// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzquxuxsumqbylrjruvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6cXV4dXhzdW1xYnlscmpydXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODc5MTksImV4cCI6MjA2Njk2MzkxOX0.8-cfMOt53-qe6ZIMPmf0Kx8gD5nOOC65XkCURj7YXUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});